services:
  frontend:
    container_name: brandify-frontend
    build: 
      context: ./Brandify-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Brandify-project:/app
    environment:
      - NODE_ENV=production